import './globals.scss';
// importing Metadata type so it can be used with our const metadata
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  // %s is our String placeholder and will be replaced with the {title: titleName} inside of About/Animals/etc
  title: { default: 'Home page | UpLeveled', template: '%s | UpLeveled' },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            {/* This is not optimized */}
            {/* <a href="/">Home</a> */}

            {/* This is optimized */}
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            {/* <Link href="/fruits">Fruits</Link> */}
            <Link href="/products">Products</Link>
            <Link href="/cart">Cart</Link>
          </div>
          {Math.floor(Math.random() * 10)}
        </nav>
        {/* Will only update on site refresh */}

        {children}
      </body>
    </html>
  );
}
